### ISSUE TITLE
Consider alternative names to `cmd!`, `cmd_unit!`, and `cmd_result!`

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#119]
This is totally subjective, so feel free to close this if you don't agree, but I kind of think the existing macro names aren't the best.

I think `cmd_unit` is actually extremely common, just judging from our own scripts, and it would be nice if it had a nicer, shorter name.

I like the names `run!(…)`, `output!(…)`, and `result!(…)`. `run` is the default for when you don't want anything, and `output` and `result` tell you what they're going to return.

Also remember to rename any instances of `cmd!` and friends in error messages, which should also probably not use the macro `!`, since these error messages can now be elicited by methods.

**Comment by soenkehahn** [comment]
I think we would want `run` (for returning unit), `run_output` (for producing `Output`) and `run_result`. And we would want the same names for the macros and the new `Input` method interface from #139.
