### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#185]
@soenkehahn mentioned this, since `cradle` is getting closer to being publicizable, and I think it's a good idea. The API will have further breaking changes, but at least by releasing 0.1.0, we have the option of making semver-backwards incompatible updates, so a 0.1.0 release should probably happen before we we shill the crate publically.

**Comment by soenkehahn** [comment]
Done: https://crates.io/crates/cradle/0.1.0
