### ISSUE TITLE
Non-string arguments

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#51]
It would be nice to be able to handle non-string arguments, which I don't think is possible at the moment. In particular, `&Path`, `PathBuf`, `&OsStr`, and `&OsString` are all common argument types.

In the standard library, arguments that are non-necessarily UTF-8 strings are of type `impl AsRef<OsStr>`. (or `fn foo<T: AsRef<OsStr>>(value: T)`. This works with pretty much everything. Ideally, this would be the type that `cradle` took for arguments, and other values, since it's the most general.

I think you can still do space-splitting on this type, although it'll get weird.

**Comment by casey** [comment]
That makes sense. And also, just because a type implements `AsRef<OsStr>` doesn't mean that the type author would necessarily want to pass the result of `x.as_ref()` as an argument. They might want to implement `CmdArgument` themselves with some other effect.

Is the best option then just to add separate implementations for `PathBuf`, `OsString`, `CString`, etcetera?

**Comment by soenkehahn** [comment]
I'm working on a PR for `Path` and `PathBuf` here: #60.

**Comment by soenkehahn** [comment]
#60 is merged, allowing `&Path` and `PathBuf`.

> Is the best option then just to add separate implementations for `PathBuf`, `OsString`, `CString`, etcetera?

Yes, I think so. I'd be happy to merge PRs for `OsString` and `&OsStr`. Less convinced about `CString`. Do you have a concrete use-case where you tried to use a `CString` with `cradle`?

**Comment by casey** [comment]
I actually thought that `Command::arg` took `CString`s, so `cradle` should accept them just because `Command` does. However, looking at it now, `CString` doesn't implement `AsRef<OsStr>`, so it can't actually be passed to `Command::arg`, so I don't think it would be useful.

**Comment by soenkehahn** [comment]
Implemented in #60 and #71.
