### ISSUE TITLE
Document `cmd_unit` better

### ISSUE THREAD

**Issue by soenkehahn** [soenkehahn/cradle#54]
'unit' isn't really a commonly used name for the type `()` in the rust community. So we should consider renaming `cmd_unit`. Any ideas for a good name?

(Here's the section of the main documentation that mentions `cmd_unit`: https://docs.rs/cradle/0.0.1/cradle/#output)

**Comment by soenkehahn** [comment]
Maybe `cmd_void!`? At least in e.g. C and Java `void` is similar to `()` in Rust. Also, Haskell has [`void`](https://www.stackage.org/haddock/lts-17.15/base-4.14.1.0/Control-Monad.html#v:void) which is kind of similar.

We could also redesign this a bit further beyond just renaming `cmd_unit!`. So we could have e.g. an `CmdOutputExt` trait that implemented `.void()`, so that you could do:

``` rust
cmd!("touch foo").void();
```

But I think that would actually be more confusing than `cmd_void!` (or whatever the name is).

**Comment by casey** [comment]
Another option would be to use completely different names the different macros entirely. Perhaps `run!()` for ignoring output, `output!()` for returning output, and `result!()` for returning the output as a result. This would also go well with #96, since then the corresponding methods could be `run`, `output`, and `result`. (Since a `cmd` and `cmd_result` are less good method names.)

**Comment by casey** [comment]
Another consideration is that perhaps `cmd_unit!` should have a name that indicates that it might panic if the command fails. I forget, can `cmd!` also panic if the command fails? Or is the panic suppressed if you use `Exit`?

**Comment by soenkehahn** [comment]
Both `cmd_unit` and `cmd` can panic. If users use `Exit` then a non-zero exit-code will not lead to a panic. But there's other reasons for panicking that remain, e.g. missing executables, trying to read invalid utf-8 into a string with `StdoutUntrimmed`, etc..

Only `cmd_result` ensures that no panics will be thrown by `cradle` code.

**Comment by soenkehahn** [comment]
I think we should keep the name `cmd_unit!` and just link to this page somewhere prominently: https://doc.rust-lang.org/std/primitive.unit.html. I'll rename this ticket.
