### ISSUE TITLE
`Exit` perhaps confusing

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#93]
Do you think it might be better to rename `Exit` to `Status`? I feel like we might have discussed this, but it isn't immediately obvious to me what `Exit` would be, just from the name. `Status` isn't perfect either, but seems a little better.

**Comment by soenkehahn** [comment]
Yeah, after googling a bit it seems 'status' is fairly widely used for this. So yes, `Status` seems slightly better.
