### ISSUE TITLE
Add `run` method to `Input`

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#96]
We discussed this a little bit, although I don't think we came to a definitive conclusion.

It might be nice to add a `run` method to `Input`, to allow doing things like this:

```rust
("ls", std::env::current_dir().unwrap()).run();
```

**Comment by soenkehahn** [comment]
This is a very intriguing idea.

I always thought that at some point we might want a non-macro interface that's an alternative to `cmd!` and friends. This kind of fits the bill. Although I was pretty convinced that we should revamp the `Config` type to follow the builder pattern. (This was suggested by @ndmitchell.) Which would _also_ provide a non-macro interface. Should we ideally do both? Or do these two ideas conflict in any way? Would it be a bit confusing to have three equally powerful ways to use the library (`cmd!` and friends, `Input::run` and a builder pattern based approach)?

**Comment by casey** [comment]
I think doing both would be okay. `.run` is very terse and convenient, `cmd!` allows using `%` to split, which is nice, and the build allows building up a command without changing the type. (You can incrementally build a command with a tuple, but the type changes each time you change the command.)

I generally don't mind multiple ways of doing things, and in this case the semantics are exactly the same, which makes it less confusing.
